# File: storage-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
    # This will be used as name of PV Hosting Volume
    name: storage-pool-1
spec:
    type: Replica1
    storage:
      - node: minikube      # node name as shown in `kubectl get nodes`
        device: /root/disk  # Device to provide storage to all PVs
